version: '3.9'

services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockerApiFestivos
    networks:
      - redApiFestivos
    ports:
      - "3000:3030"

networks:
  redApiFestivos:
    external: true
