name: Setup Express API

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build and Run Express API
      run: |
        docker-compose up --build -d